### ISSUE TITLE
[JS-951] ember-local-storage config is not correctly handle when not default

### ISSUE THREAD

**Issue by romgere** [peopledoc/ember-feature-controls#111]
Features values are not correctly restored by instance-initializer when `ember-local-storage` is used with `namespace` or  `keyDelimiter` options.

The reason is :

feature-controls component uses `storageFor` from `ember-local-storage` to write values in locale Store (https://github.com/peopledoc/ember-feature-controls/blob/master/addon/components/feature-controls.js#L6). 
`storageFor` take into account the `ember-local-storage` config to write the key at the right place in locale storage (with correct namespace and/or delimiter).

In other hand, the instance initializer uses `getStorage` & get value with the `storage:feature-controls` key wich does not take into account the `ember-local-storage` config (https://github.com/peopledoc/ember-feature-controls/blob/master/addon/instance-initializers/load-feature-controls.js#L9)

It results with a desynchronisation between `ember-feature-controls` & `ember-feature-flags` as the value are not correctly restored onto `ember-feature-flags` `features` service.

**Comment by BlueCutOfficial** [comment]
@romgere can you create a JIRA ticket on Tribe JS board? 🙏

**Comment by romgere** [comment]
Sure I will

**Comment by romgere** [comment]
Done : [JS-951](https://people-doc.atlassian.net/browse/JS-951)
